### PR TITLE
(Fix) branch-agnostic generate initial script

### PR DESCRIPTION
**Pull request by vbaranov**
As a continuation of discussion of https://github.com/poanetwork/poa-scripts-moc/pull/17

**Problem**: `generateInitialKey` script has own config with ABI and contract address
**Solution**: get ABI and contract addresses from single endpoint: chain-spec repo

_Example_:
NETWORK=core RPC=http://127.0.0.1:8545 node generateInitialKey.js

```
const network = process.env.NETWORK || 'core'
const rpc = process.env.RPC || 'http://127.0.0.1:8545'
```

### CODE REVIEW

**Review by phahulin — COMMENTED** [review]
While this will  greatly simplify managing of forks, I have a security concern: url is fetched each time the script runs i.e. every hour - if someone breaks in our github repo, can [s]he substitute addresses and get tokens sent to another contract before we can take any measures? Pinging @igorbarinov for the second opinion.

Also some minor remarks: `organization`, `repoName` variables are hard-coded while `NETWORK` and `RPC` are passed via env var. I'd suggest we move them all in a new _config file outside version control_ (in `.gitignore`) -
 that is much easier to manage. Playbook will create this file and populate necessary values during installation.

**Comment by igorbarinov** [comment]
I'm against scheduled pulling from any repo to Core nodes

**Comment by rstormsf** [comment]
@igorbarinov @vbaranov @phahulin 
I'm against pulling repo for Core, I'm also against hard coding the values into the repos.
How about we pass thru env vars and when a moc needs to do something, he needs to know this information and input it into the playbook.

Lets say we leave abi file here, but addresses is passed via playbook and if moc wants to update it, he can manually change it in his node in some generated config file.

**Comment by phahulin** [comment]
The issue in this  PR is that pulling is performed repeatedly without user interaction. Also, I don't like env vars :smile: they are easy to make mistake with (long command lines) and only support strings.

Here's the structure I proposed in the first PR about this (just an example - one simple script):

```
myscript/
--- .gitignore
--- contract-data/
------- contracts.json
------- abis/
----------- KeysManager.abi.json
----------- BallotsStorage.abi.json
----------- ...
--- script.js
```
1. names of files in `contract-data` and their structure is fixed

2. `.gitignore` must contain `contract-data` folder
```
...
contract-data
...
```

3. `contract-data` is created by playbook during initial installation, and all necessary files are downloaded _once_ (spec, bootnodes.txt and other files are downloaded during installation anyway, so it doesn't seem to bring any additional security risk).
_There is probably a little caveat - I don't yet know if it's possible to download a whole folder like `abis` from github_

4. `script.js` uses those files by their fixed names:
```js
const KEYS_MANAGER_ADDRESS = require('./contract-data/contracts.json').KEYS_MANAGER_ADDRESS;
const KEYS_MANAGER_ABI = require('./contract-data/abis/KeysManager.abi.json');
```
so that there is no direct mention of network name or any of the contract addresses.

5. for future forks - create a new playbook that redownloads `contract-data`.

What do you think about it?

**Pull request closed without merging**
